name: Signup & Login Functionality
on:
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch
      - ic-final

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: package.json
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run frontend manual tests
        run: node ./frontend/src/__tests__/login.test.js
        
  backend-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package.json
      - name: Install dependencies
        run: npm install
      - name: Ensure express.js works
        run: npm install express
      - name: Ensure mysql2 works
        run: npm install mysql2
      - name: Ensure cors works
        run: npm install cors --save
      - name: Ensure dotenv works
        run: npm install dotenv
      - name: Wait for MySQL
        run: |
          until mysqladmin ping --host=127.0.0.1 --user=test_user --password=test_pass; do
            sleep 1  # Waits for MySQL to be ready
          done
      - name: Run backend manual tests
        run: node backend/tests/login.test.js
